version: '3.4'
services:
  fastapi-vscode-debug-setup:
    image: sashakang/scheduler
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
        - scheduling-vol:/credentials
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn scheduling_server:app --host 0.0.0.0 --port 8000 --reload"]
    # for testing
    environment:
      - APP_MESSAGE=Hello scheduler
    ports:
      - 8000:8000
      - 5678:5678
volumes:
  scheduling-vol:
    external: true